name: OnePlus SM8750 Build SuKiSu SUSFS
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8750'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_13'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'sun'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '6.6'
      #kernelsu_branch:
        #description: "Sukisu分支版本"
        #required: true
        #type: choice
        #options:
          #- Stable
          #- Dev
        #default: 'Dev'
      KERNEL_NAME:
        description: "修改内核名称"
        required: true
        default: '-android15-8-g013ec21bba94-abogki383916444'
      build-timestamp:
        description: "修改构建时间"
        required: true
        default: 'Tue Dec 17 23:36:49 UTC 2024'
      use_kpm:
        description: '是否开启KPM功能?'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: Configure Git
        run: |
         git config --global user.name "build"
         git config --global user.email "3028172686@qq.com"

      - name: Install dependencies
        run: |
         sudo apt update && sudo apt upgrade -y
         sudo apt install -y python3 git curl

      - name: Install repo tool
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
         mkdir kernel_workspace && cd kernel_workspace
         repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
         repo --trace sync -c -j$(nproc --all) --no-tags
         rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
         rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
         
      - name: Set up SukiSU
        run: |
         cd kernel_workspace/kernel_platform
         #if [[ "${{ inputs.kernelsu_branch }}" == "Stable" ]]; then BRANCH="-s susfs-stable"
          #echo "::notice::✔ 已选择 Stable 分支"
         #elif [[ "${{ inputs.kernelsu_branch }}" == "Dev" ]]; then BRANCH="-s susfs-dev"
          #echo "::notice::✔ 已选择 Dev 分支"
          #fi
         #curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash $BRANCH
         curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
         cd ./KernelSU
         KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10606)
         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
         export KSU_VERSION=$KSU_VERSION
         sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
         echo "::notice::✔ Sukisu版本：$KSU_VERSION"
        
      - name: Set up susfs
        run: |
           cd kernel_workspace
           #git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}
           git clone https://github.com/mehu3dhokia/susfs4ksu.git
           git clone https://github.com/SukiSU-Ultra/SukiSU_patch.git

           cd kernel_platform
           #cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
           cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch ./common/
           cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
           #lz4kd
           #cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./common/include/linux
           #cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./common/lib
           #cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto
           #cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./common/lib/
           
           # Apply patches
           cd ./common

           sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
           sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch

           #patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
           patch -p1 < 50_add_susfs_in_gki-android15-6.6.patch || true
           
           cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
           patch -p1 < syscall_hooks.patch
           
           echo "完成"
#           rm -rf ./fs/namespace.c
#           rm -rf ./fs/namespace.c.rej
#           cp ../../kernel_patches/namespace.c ./fs
#           echo "复制namespace.c完成"

#      - name: Apply lz4kd Patches
#        run: |
#          cd kernel_workspace/kernel_platform/common
#          if [[ "${{ github.event.inputs.lz4kd }}" == "true" ]]; then
#          cp ../../SukiSU_patch/other/zram/zram_patch/${{ github.event.inputs.KERNEL_VERSION }}/lz4kd.patch ./
#          patch -p1 -F 3 < lz4kd.patch || true
#          echo "::notice::✔ lz4kd补丁安装完成"
#          elif [[ "${{ github.event.inputs.lz4kd }}" == "true" ]]; then
#          echo "::notice::✔ 跳过lz4kd补丁安装"
#          fi
           
      - name: Add SUSFS Configuration Settings
        run: |
          cd kernel_workspace/kernel_platform
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [ "${{ inputs.use_kpm }}" == "true" ]; then
            echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "::notice::✔ 开启kpm"
          elif [ "${{ inputs.use_kpm }}" == "false" ]; then
            echo "::notice::✔ 未开启kpm"
          fi

          # Add VFS configuration settings
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Add SUSFS configuration settings
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "
